config/routes.rb
Rails.application.routes.draw do

  #devise_for :sms_users
  resources :login_devices
  get 'activities/index'
  match '*path', via: [:options], to: lambda {|_| [204, { 'Content-Type' => 'text/plain' }]}
  resources :track do
    member do
      get :get_coordinates
    end
  end
  namespace :admin do
    root 'dashboard#index'
    devise_scope :user do
      get '/sign_in' => "/users/sessions#new" , as: :sign_in
      get '/sign_up' => "/users/registrations#new", as: :sign_up
    end
    devise_scope :sms_user do
      get '/sign_in' => "/sms_users/sessions#new" , as: :sms_sign_in
      get '/sign_up' => "/sms_users/registrations#new", as: :sms_sign_up
    end
    get "/dashboard/cargo-owners" => "dashboard#cargo_owners" , as: :cargo_owners
    get "/dashboard/fleet-owners" => "dashboard#fleet_owners" , as: :fleet_owners
    post "/dashboard/mark-verified/:company_id" => "dashboard#mark_verified", as: :mark_verified
    post "/dashboard/mark-featured/:company_id" => "dashboard#mark_featured", as: :mark_featured
    post "/dashboard/mark-blacklisted/:company_id" => "dashboard#mark_blacklisted", as: :mark_blacklisted
    post "/dashboard/tax_invoice/:company_id" => "dashboard#tax_invoice", as: :tax_invoice
    post "/dashboard/mark-safe-for-cash-on-delivery/:company_id" => "dashboard#mark_safe_for_cash_on_delivery", as: :mark_safe_for_cash_on_delivery
    get "/dashboard/show-user/:user_id" => "dashboard#show_user", as: :show_user
    get "/dashboard/edit-user/:user_id" => "dashboard#edit_user", as: :edit_user
    patch "/dashboard/update-user/:user_id" => "dashboard#update_user", as: :update_user
    get "/dashboard/cargo-contracts/:company_id" => "dashboard#cargo_contracts", as: :cargo_contracts
    post "/payments/mark-paid-by-cargo/:shipment_id" => "payments#mark_paid_by_cargo", as: :mark_paid_by_cargo
    post "/payments/mark-lorryz-comission-received/:shipment_id" => "payments#mark_lorryz_comission_received", as: :mark_lorryz_comission_received
    post "/payments/mark-paid-to-fleet/:shipment_id" => "payments#mark_paid_to_fleet", as: :mark_paid_to_fleet
    post "/payments/cancel_penalty_amount_received/:shipment_id" => "payments#cancel_penalty_amount_received", as: :cancel_penalty_amount_received

    resources :pages
    resources :invoices , only: [:show]
    resources :countries , except: [:destroy]
    resources :vehicle_types, except: [:destroy]
    resources :locations
    resources :change_destination_requests
    resources :shipments do 
      member do 
        delete :cancel
      end
      collection do
        post :get_bulk_coordinates
      end
    end
    resources :users
    resources :payments
  end
  namespace :cargo do
    root 'dashboard#index'
    resources :payments
    resources :shipments do
      collection do
        get :posted
        get :ongoing
        post :calculate_fare
        get :upcoming
        get :completed
        post :get_bulk_coordinates
      end
      member do
        get :get_coordinates
        get :cancel
        get :update_destination
        patch :update_destination
      end
    end
    resources :bids do
      member do
        post :accept
        post :reject
      end
    end
    resources :dashboard , only: [:index]
  end
  namespace :fleet do
    root 'shipments#posted'
    resources :payments
    resources :shipments do
      collection do
        get :posted
        get :active
        get :ongoing
        get :won
        get :completed
      end
      member do
        get :quit_bid
        get :assign_vehicle
        get :cancel
        get :get_coordinates
        post :not_interested
      end
      resources :bids do
        collection do
          post :bid_details
          get :bidNow
          # get :notInterested
        end
      end
    end
    resources :drivers do
      collection do
        post :register_as_driver
      end
    end
    resources :vehicles do
      collection do
        get :vehicle_types
      end
      member do
        post :change_driver
        get :change_driver
      end
    end

    resources :dashboard , only: [:index]
  end
  resources :countries do
    collection do
      get "location/:location_id" => "countries#location"
      get :get_vehicles_by_country
      # get :vehicles
    end
  end

  devise_for :users, controllers: {:invitations => 'users/invitations',passwords: 'users/passwords', sessions: 'users/sessions', registrations: 'users/registrations',confirmations: 'users/confirmations'   }

  devise_scope :user do
    # match "user/account" => "user#account", as: :user_account, via: [:get, :post]
    match '/users/mobile-verification' => 'users/registrations#mobile_verification' , via: [:get, :post]
    get '/users/send-verification-code/:user_id' => 'users/registrations#send_verification_code', as: :send_verification_code
    match '/sign_up' => "users/registrations#new", as: :sign_up,via: [:get, :post]
  end

  devise_for :sms_users, controllers: {passwords: 'sms_users/passwords', sessions: 'sms_users/sessions', registrations: 'sms_users/registrations',confirmations: 'sms_users/confirmations'}
  devise_scope :sms_user do
    # match "user/account" => "user#account", as: :user_account, via: [:get, :post]
    #match '/users/mobile-verification' => 'users/registrations#mobile_verification' , via: [:get, :post]
    #get '/sms_users/send-verification-code/:user_id' => 'sms_users/registrations#send_verification_code', as: :send_verification_code
    match '/sign_up' => "sms_users/registrations#new", as: :sms_user_sign_up,via: [:get, :post]
  end
  
  resources :companies, :only => [  ] do
    collection do
      post :add_company_information
      patch :add_company_information
      post :add_individual_information
      patch :add_individual_information
      get :edit
      get :get_individual_information
      get :get_company_information
      put :presign_upload
    end
  end
  match "/ratings" => "rating#rate", via: [:get, :post] , as: :ratings_shipment
  resources :invoices , only: [:show]
  namespace :api do
  	namespace :v1 do
      devise_for :users, controllers: { sessions: 'api/v1/users/sessions', registrations: 'api/v1/users/registrations'  }
      devise_for :sms_users, controllers: { sessions: 'api/v1/sms_users/sessions', registrations: 'api/v1/sms_users/registrations'  }

      resources :ratings do
      end
      resources :invoices do 
        member do 
          post :send_in_email
        end
      end
      namespace :cargo do
        resources :companies do
          resources :payments
          resources :shipments do
            collection do
              get :posted
              get :ongoing
              get :upcoming
              post :calculate_fare
              get :completed
            end
            resources :bids do
              member do
                post :accept
                post :reject
              end
            end
          end
        end
      end
      namespace :fleet do
        resources :drivers do
          collection do
            post :register_as_driver
            post :upcoming_shipments
            post :ongoing_shipments
            post :completed_shipments
            post :update_vehicle_status
            post :report_problem
            post :payment_received
          end
        end
        resources :vehicles do 
          collection do 
            get :vehicle_types
            post :change_driver
            get :fetch_nearby
          end
          member do
            put :update_lat_lng
          end
        end 
        resources :companies do
          resources :payments
          resources :shipments do
            collection do
              get :posted
              get :active
              get :won
              get :ongoing
              get :ongoing_vehicles
              get :completed
              
            end
            member do 
              post :quit_bid
              put :update_destination
              get :vehicles
              post :not_interested
            end
          resources :bids do
            collection do
              get :bidNow
              get :notInterested
            end
          end
          end
        end
      end

      namespace :faculty do
          resource :albums do
              get :show_all_albums
              patch :delete_album
          end

          resource :class_sections do
              get :show_all
          end

          resource :course_diaries do
          end

          resource :faculty_timetable do
            get :get_faculty_timetable
          end

          resource :leave_applications do
              get :show_all_requested_leaves
              get :get_leaves_by_date
              patch :update_leave_status
          end

          resource :parent_teacher_meetings do
            get :show_all_requested_meetings
            patch :set_appointment_date
          end
          resource :parent_teacher_meeting_comments do
            get :show_all_comments
          end

          resource :picture do
              patch :delete_pictures
          end

          resource :section_courses do
              get :get_faculty_teached_class
              get :get_faculty_teached_section
              get :get_section_courses
          end

          resource :section_notices do
              get :get_class_section_teacher
          end

          resource :student_attendance do
            post :create_all
          end
      end

      namespace :van_driver do
          resources :van_drivers do

          end
          resources :vans do
            collection do
              post :update_status
              post :update_van_location
            end
          end
      end

      namespace :parent do
          resource :albums do
              get :show_all_albums
          end

          resource :course_diaries do
              get :get_student_diaries
          end

          resource :leave_applications do

app/controllers/api/v1/fleet/bids_controller.rb
class Api::V1::Fleet::BidsController < Api::V1::ApiController
  before_action :set_bid, only: [:show, :edit, :update, :destroy]

  # GET /bids
  # GET /bids.json
  def index
    @bids = shipment.available_bids
  end

  # GET /bids/1
  # GET /bids/1.json
  def show
  end

  # GET /bids/new
  def new
    @bid = Bid.new
  end

  # GET /bids/1/edit
  def edit
  end

  # POST /bids
  # POST /bids.json
  def create
    Shipment.find(params[:shipment_id]).bids.where(:company_id =>  params[:company_id]).delete_all
    @bid = shipment.bids.new(bid_params.merge(company_id: params[:company_id]))
    @bid.save
    @bid.errors.blank? ? ( render "create" , status: :ok ) : (render json: { errors: @bid.errors.full_messages }, status: :bad_request)
    
  end

  # PATCH/PUT /bids/1
  # PATCH/PUT /bids/1.json
  def update
    respond_to do |format|
      if @bid.update(bid_params)
        format.html { redirect_to @bid, notice: 'Bid was successfully updated.' }
        format.json { render :show, status: :ok, location: @bid }
      else
        format.html { render :edit }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bids/1
  # DELETE /bids/1.json
  def destroy
    @bid.destroy
    respond_to do |format|
      format.html { redirect_to bids_url, notice: 'Bid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bid
      @bid = Bid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bid_params
      params.require(:bid).permit(:company_id, :amount, :status, :detention, :shipment_id)
    end

    def company 
      company = Company.find(params[:company_id])
    end
    
    def shipment
      Shipment.find_by_id(params[:shipment_id])
    end
end

app/controllers/api/v1/fleet/drivers_controller.rb
class Api::V1::Fleet::DriversController < Api::V1::ApiController
	before_action :set_vehicle, only: [:show,:destroy]
	before_action :set_shipment, only: [:update_vehicle_status,:report_problem,:payment_received]

	def index		
		if params[:assignment]
			@drivers =  User.includes(:vehicle).where({vehicles: {user_id: nil}}).where(:company_id => @user.company_id,role:User.role.find_value(:driver).value)
			if params[:driver_id].present? && params[:driver_id] != 'null'
				current_assigned_driver = [User.find(params[:driver_id])]
				@drivers = @drivers | current_assigned_driver
			end
		else
			@drivers = User.where(:company_id => @user.company_id,role:User.role.find_value(:driver).value)
		end

		render 'index', status: :ok
	end

	def register_as_driver
		full_name = params[:driver][:full_name]
		firstname = full_name.split(" ")[0] rescue ''
		lastname = full_name.split(" ").drop(1).join("") rescue ''		
		mobile = params[:driver][:mobile]

		user = User.find_by_mobile(mobile)

		if user
			render json: {error: "Mobile number has already been taken"}, status: :unprocessable_entity	
		else
			
			password = (0...8).map { ('a'..'z').to_a[rand(26)] }.join
			@driver = User.new(:mobile => mobile, :first_name=> firstname,:last_name => lastname,
								:password => password, :password_confirmation => password,:role => User.role.find_value(:driver).value,
								:company_id => @user.company_id,:country_id => @user.country_id)

			@driver.build_driver_information(driver_information_params)
			@driver.save
			@driver.driver_login_sms()
			render json: @driver, status: :ok	
		end
		

	end

	def show
		
		if @driver = User.find_by_id(params[:id])
			render 'show', status: :ok
		else
			render json: {error: "Driver not found" },status: :ok			
		end
	end

	def update
		full_name = params[:driver][:full_name]
		firstname = full_name.split(" ")[0] rescue ''
		lastname = full_name.split(" ").drop(1).join("") rescue ''	
		
		mobile = params[:driver][:mobile]
		@driver = User.find_by_mobile(mobile)

		if @driver

			driver = @driver.update_attributes( 
								:first_name=> firstname,
								:last_name => lastname,
								:company_id => @user.company_id,
								:country_id => @user.country_id,
								password: params[:driver][:password],
								password_confirmation: params[:driver][:confirm_password]
								)
			driver_information = @driver.driver_information
			driver_information.update_attributes!(driver_information_params)
			
			if driver && driver_information
			  render "show" , status: :ok 
			else
			  render json: @driver.errors.full_messages, status: :unprocessable_entity 
			end	
		else
			render json:{error: "Driver not found" }  , status: :ok
		end
	end

	def destroy
	  @driver.destroy
	  respond_to do |format|
	    format.json { head :no_content }
	  end
	end


	def upcoming_shipments
		@shipments = @user.assigned_shipments.vehicle_assigned.uniq
		@shipments = paginate(@shipments)
		render 'driver_shipments', status: :ok
	end


	def ongoing_shipments
		@shipments = @user.assigned_shipments.ongoing.uniq
		@shipments = paginate(@shipments)
		render 'driver_shipments', status: :ok
	end

	def completed_shipments
		@shipments = @user.assigned_shipments.completed.uniq
		@shipments = paginate(@shipments)
		render 'driver_shipments', status: :ok
	end

	def paginate(shipments)
		Kaminari.paginate_array(shipments).page(params[:page]).per(5)
	end

	def update_vehicle_status
		
		if route_inprogress?

			@shipment.ongoing! unless @shipment.ongoing?
			update_transport_status
			render_status({shipment: @shipment})
		elsif route_completed?
			shipment_distance_from_vehicle <= 5 ? shipment_completed! : render_status({error: "Shipment is not within 5km to destination"})
		end
	end

	def report_problem

		fleet_owner = @shipment.fleet.fleet_owner
		admin = User.find_by_email("admin@lorryz.com")

		@user.report_problem(fleet_owner,admin,@shipment)
		render json: {success: "Pasword has been sent your phone number"}
	end

	def payment_received
		@shipment.paid_by_cargo = true
		@shipment.paid_to_fleet = true
		@shipment.save
		render json: {success: "Payment Succesfully received"}
	end

	private
	  # Use callbacks to share common setup or constraints between actions.
	  def set_vehicle
	    @driver = User.find_by(id: params[:id])
	end

	def driver_information_params
	  params.require(:driver).permit(:national_id, :expiry_date, :license, :license_expiry, :user_id, {license_documents: []}, {emirate_documents: []}, :avatar)
	end

	def set_shipment
		@shipment = Shipment.find_by(id: params[:shipment_id])
	end

	def route_inprogress?
		statues = ['start','loading','enroute','unloading']
		statues.include?(params["status"])
	end

	def route_completed?
		params["status"] == 'finish'
	end

	def shipment_completed!
		update_transport_status
		
		if @shipment.all_vehicles_at_destination?
			@shipment.completed! unless @shipment.completed?
		end
		
		render_status({shipment: @shipment})
	end

	def shipment_distance_from_vehicle
		@shipment.distance_from_vehicle(params[:vehicle_id])
	end

	def update_transport_status
		@shipment.shipment_vehicles.where(vehicle_id: params[:vehicle_id]).update(status: params[:status])
	end

	def render_status(status)
		render json: status  , status: :ok 
	end

end

app/helpers/api/v1/fleet/payments_helper.rb
module Api::V1::Fleet::PaymentsHelper
end

app/helpers/api/v1/fleet/shipments_helper.rb
module Api::V1::Fleet::ShipmentsHelper
end

app/helpers/fleet/bids_helper.rb
module Fleet::BidsHelper
end

app/helpers/fleet/dashboard_helper.rb
module Fleet::DashboardHelper
end

app/helpers/fleet/drivers_helper.rb
module Fleet::DriversHelper
end

app/helpers/fleet/payments_helper.rb
module Fleet::PaymentsHelper
end

app/helpers/fleet/shipments_helper.rb
module Fleet::ShipmentsHelper
end

app/helpers/fleet/vehicles_helper.rb
module Fleet::VehiclesHelper
end

app/views/fleet/drivers/_form_fields.html.erb
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-6">
        <div class="card card-primary">
          <div class="card-header">
            <h3 class="card-title"><%= action %> Driver</h3>
          </div>
          <form role="form">
            <div class="card-body">
              <div class = "avatar12">
                <% if @driver.driver_information.present? and @driver.driver_information.avatar.present? %>
                  <div class= "">
                    <%= image_tag(@driver.driver_information.avatar , class: "avatar" )%>
                  </div>
                <%end%>
                <%= f.fields_for "driver_information" do |f| %>
                  <div class="field form-group">
                    <%= f.label :avatar, "Profile Picture" %><br>
                    <%= f.hidden_field "avatar", class: "js-signed-upload-value" , value: @driver.driver_information.avatar %>
                    <input type="file" class="js-signed-upload" data-presign-url="<%=  presign_upload_companies_path %>" />
                    <p class="js-signed-upload-status"></p>
                  </div>
                <%end%>
              </div>
              <div class="form-group">
                <%= f.label "*" , class: "label_required"%>
                <%= f.label :country %>
                <%= f.collection_select("default country", Country.all, :id, :display_name,{:prompt => "*Country", selected: current_user.country_id }, { class: "form-control" ,disabled: true} )%>
              </div>
              <div class="form-group">
                <%= f.label "*" , class: "label_required"%>
                <%= f.label "Driver's Mobile No.", "Driver's Mobile No." %>
                <%= f.number_field :login , class: "form-control", placeholder: "*Driver's Mobile Number" ,type: :number,pattern: "[0-9]", required: true%>
              </div>
              <div class="form-group">
                <%= f.label "*" , class: "label_required"%>
                <%= f.label :full_name , "Full Name"%>
                <% action == "Add" ? (full_name = nil) : (full_name = @driver.full_name)%>
                <%= f.text_field :full_name , class: "form-control", placeholder: "*Driver's Full Name", value: full_name , required: true%>
              </div>
              <div class="form-group">
                <%= f.label "*" , class: "label_required"%>
                <%= f.label :national_id, "Driver's Emirates ID No." %>
                <%nationl_id = @driver.driver_information.national_id rescue ""%>
                <%= f.text_field :national_id , class: "form-control", placeholder: "*Driver's Emirates ID No.", value: nationl_id, required: true %>
              </div>
              <div class="form-group has-feedback">
                <%= f.label "*" , class: "label_required"%>
                <%= f.label 'user[expiry_date]', "Expiry Date" %>
                <% expiry_date =  @driver.driver_information.expiry_date rescue ""%>
                <%= text_field_tag "user[expiry_date]","", class: "datepicker form-control" ,placeholder:  "*Expiry Date" , required: true , value: expiry_date%>
              </div>
              <div class = "form-group has-feedback">
                <%= f.fields_for "driver_information" do |f| %>
                  <div class="form-group has-feedback attachment">
                    <%= f.label "*" , class: "label_required"%>
                    <%= f.label :emirate_documents , "Upload Front & Back side of Emirates ID"%><br>
                    <%= f.hidden_field :emirate_documents, multiple: true, class: "js-signed-upload-value" , value: @driver.driver_information.emirate_documents %>
                    <input type="file" class="js-signed-upload" multiple data-presign-url="<%= presign_upload_companies_path %>" , required=true/>
                    <div class="attached_files container">
                      <p class="js-signed-upload-status">
                        <% if @driver and @driver.driver_information.emirate_documents.present? %>
                          <ul class="documents_list">
                            <% @driver.driver_information.emirate_documents.each do |doc| %>
                              <li>
                                <a target="_blank" href="<%= doc %>">
                                  <span class="remove_thumbnail">x</span>
                                  <img src="<%= doc %>" alt="document" class="document_thumbnail">
                                </a>
                              </li>
                            <% end %>
                          </ul>
                        <br><br><br>
                        <% end %>
                      </p>
                    </div>
                  </div>
                <% end %>
              </div>
              <div class="form-group has-feedback">
                <%= f.label "*" , class: "label_required"%>
                <%= f.label "user[license_expiry]","Driving Licence Number" %>
                <% license = @driver.driver_information.license rescue ""%>
                <%= text_field_tag "user[license]","", class: " form-control" ,placeholder:  "*Driving Licence Number" ,value: license, required: true%>
              </div>
              <div class="form-group has-feedback">
                <%= f.label "*" , class: "label_required"%>
                <%= f.label "user[license]","Driving Licence Expiry Date" %>
                <% license_expiry =  @driver.driver_information.license_expiry rescue ""%>
                <%= text_field_tag "user[license_expiry]","", class: "datepicker form-control" ,value: license_expiry,placeholder:  "*Driving Licence Expiry Date" , required: true%>
              </div>
              <div class="form-group has-feedback">
                <%= f.fields_for "driver_information" do |f| %>
                  <div class="form-group has-feedback attachment">
                    <%= f.label "*" , class: "label_required"%>
                    <%= f.label :license_documents , "Upload scanned copy of your License" %><br>
                    <%= f.hidden_field :license_documents , multiple: true, class: "js-signed-upload-value", value: @driver.driver_information.license_documents %>
                    <input type="file" class="js-signed-upload" multiple data-presign-url="<%= presign_upload_companies_path %>" required=true/>
                    <div class="attached_files container">
                      <p class="js-signed-upload-status">
                        <% if @driver and @driver.driver_information.license_documents.present? %>
                        <ul class="documents_list">
                          <% @driver.driver_information.license_documents.each do |doc| %>
                            <li>
                              <a target="_blank" href="<%= doc %>">
                                <span class="remove_thumbnail">x</span>
                                <img src="<%= doc %>" alt="document" class="document_thumbnail">
                              </a>
                            </li>
                          <% end %>
                        </ul>
                        <br><br><br>
                      <% end %>
                      </p>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="card-footer">
              <%= f.submit submit_button_text , class: "btn btn-primary" %>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

<script>
    $(".remove_thumbnail").click(function (e) {
        e.preventDefault()
        value = $(this).parents(".form-group").find(".js-signed-upload-value").val()
        value = value.split(" ")
        remove_url = $(this).parents("a").attr("href")
        index = value.indexOf(remove_url)
        value.splice(index, 1)
        $(this).parents(".form-group").find(".js-signed-upload-value").val(value.join(" "))
        $(this).parents("a").addClass("hide")
    })
</script>

app/views/fleet/drivers/edit.html.erb
<div class="content-wrapper">
  <%= form_for @driver, url: fleet_driver_path(@driver.id)  do |f|%>
      <%= render partial: "form_fields" , locals: {f: f , action: "Edit", submit_button_text: "Update Driver"}%>
  <%end%>

</div>

app/views/fleet/drivers/index.html.erb
<div class="content-wrapper" style="min-height: 539px;">
  <section class = "content">
    <div class = "container-fluid">
      <div class = "row1">
        <div class = "card-body">
          <div class="card">
            <div class="balance-header">
              <h1>Drivers Listing</h1>
            </div>

            <!-- /.card-header -->
            <div class="card-body">
              <table id="shipments_listing" class="table table-bordered table-striped" data-page-length='10'>
                <thead>
                <tr>
                  <th>Name</th>
                  <th>ID No.</th>
                  <th>Mobile No.</th>
                  <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                  <%@drivers.each do |driver|%>
                    <tr>
                      <td><%= driver.full_name %></td>
                      <td><%=driver.driver_information.national_id %></td>
                      <td><%=driver.mobile %></td>
                      <td>
                        <div class = "btn-group">
                          <%# link_to "Chat Now","/", class: "btn  btn-secondary btn-flat"  %>
                          <%= link_to "Edit",edit_fleet_driver_path(driver) , class: "btn btn-success btn-flat" %>
                          <%if driver.vehicle.present? %>
                            <div title="Driver is Assigned to Vehicle" rel="tooltip">
                              <%= link_to "Delete" ,"#", format: :html,class: " disabled btn  btn-primary btn-flat " %>
                            </div>
                          <%else%>
                            <%= link_to "Delete" ,fleet_driver_path(driver.id ),  method: :delete, format: :html,class: "btn  btn-primary btn-flat "  %>
                          <%end%>
                        </div>
                      </td>
                    </tr>
                  <%end%>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/fleet/drivers/new.html.erb
<div class="content-wrapper">
  <%= form_for @driver, url: fleet_drivers_path  do |f|%>
    <%= render partial: "form_fields" , locals: {f: f , action: "Add", submit_button_text: "Add Driver"}%>
  <%end%>

</div>